### PR TITLE
refactor: use local snapshot of @google-cloud/deploy package

### PR DESCRIPTION
**Pull request by hegemonic**
This PR eliminates the need to clone the `googleapis/nodejs-deploy` repo before running the tests, which cuts several seconds off of their run time.

The interesting changes are in 3172864d7655222564dc6520f4efd8927241cf33, which is small. The other commits, which are gigantic, just use `git subtree` to add a snapshot of https://github.com/googleapis/nodejs-deploy to the test fixtures.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com//issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Review by dansaadati — CHANGES_REQUESTED** [review]
Really appreciate this, should speed up our tests!

Could we remove some of the lint, kokoro, and any other extra dirs? We originally decided to clone the repo so we didn't need to maintain this in source, but given the test speed benefits, I think it's worth bringing this in if we can minimize what we check in.

**Comment by hegemonic** [comment]
> Could we remove some of the lint, kokoro, and any other extra dirs? We originally decided to clone the repo so we didn't need to maintain this in source, but given the test speed benefits, I think it's worth bringing this in if we can minimize what we check in.

Done.

I hear you re: maintenance. Hopefully using `git subtree` will make it a bit easier to update the code when necessary.

**Review by dansaadati — APPROVED** [review]
Sorry for the delay! LGTM

**Comment by dansaadati** [comment]
Thanks again Jeff for adding this!

**Pull request merged**
